### PR TITLE
Fix permissions on AlertManager sidecar

### PR DESCRIPTION
**Pull request by gburton1**
**What this PR does**:
This restores the user that the alertmanager sidecar runs as to 0. It had been changed during this refactor in https://github.com/cortexproject/cortex-helm-chart/pull/227/files for the 1.0.0 release:
```
-    securityContext:
-      runAsUser: 0
+    containerSecurityContext:
+      enabled: true
+      readOnlyRootFilesystem: true
```

**Which issue(s) this PR fixes**:
Fixes https://cloud-native.slack.com/archives/CCYDASBLP/p1642492446058600

**Checklist**
- [x ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by nschad — COMMENTED** [review]
It's not necessary if cortex is running as root. I wanted to do the same thing but it works like this out of the box See: #315

**Comment by nschad** [comment]
In my deployment we have the following:

* sidecar runs as configured nobody:nobody
* cortex runs as root:root
```
~ $ ls -alh /data/
total 24K    
drwxrwxrwx    3 root     root        4.0K Feb 16 14:50 .
drwxr-xr-x    1 root     root        4.0K Feb 16 14:50 ..
drwxr-xr-x    2 nobody   nobody      4.0K Feb 16 21:20 fake
~ $ ls -alh /data/fake
total 36K    
drwxr-xr-x    2 nobody   nobody      4.0K Feb 16 21:20 .
drwxrwxrwx    3 root     root        4.0K Feb 16 14:50 ..
-rw-r--r--    1 nobody   nobody      1.4K Feb 16 14:50 fake.yaml
-rw-r--r--    1 root     root         589 Feb 16 21:20 notifications
-rw-r--r--    1 root     root           0 Feb 16 21:20 silences
```
so cortex actually has more permission thus no error. I do understand if it were the other way around tho. If cortex were to create the `fake` folder with root:root then yeah it would not work

**Comment by gburton1** [comment]
Hmm. This means that the change was backwards incompatible to past live deployments of this chart, unless action is taken to blow away existing files in all environments, since the existing files were created under a past version of Cortex chart when the sidecar was user 0, and therefore maintain that older ownership.

Although this doesn't quite explain the experience of Charlie on the thread, since he was creating a new deployment from scratch. Unless maybe he had started on an earlier version too.

**Comment by nschad** [comment]
> Hmm. This means that the change was backwards incompatible to past live deployments of this chart, unless action is taken to blow away existing files in all environments, since the existing files were created under a past version of Cortex chart when the sidecar was user 0, and therefore maintain that older ownership.

Yeah okay that makes sense. Looks like we missed that one :(. To be fair it was a major release, haha :D

**Comment by gburton1** [comment]
Not sure why the linter check is unhappy

**Comment by nschad** [comment]
> Not sure why the linter check is unhappy

Run `helm-docs` in the repo to update the README.md https://github.com/norwoodj/helm-docs. But I don't if we will acccept this PR. Preferably we don't want anything to run as root.

**Comment by disambiguationuk** [comment]
Interesting, the only way we can get this to work is to use this `runAsUser: 0` override too.

**Pull request closed without merging**
