### PR TITLE
update docs also in the tmpl file

### PR DESCRIPTION
**Pull request by ShuzZzle**
Signed-off-by: ShuzZzle <niclas.schad@gmail.com>

**What this PR does**:

Triggerhappy me forgot to update the changes in #181 also in the template. This pr should fix that

**Which issue(s) this PR fixes**:
Persist #181

### CODE REVIEW

**Comment by kd7lxl** [comment]
Should also update values.yaml to document these options: https://github.com/cortexproject/cortex-helm-chart/pull/181/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R300

**Comment by ShuzZzle** [comment]
> Should also update values.yaml to document these options: https://github.com/cortexproject/cortex-helm-chart/pull/181/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R300

Yeah that's exactly the Issue. The generated output often does not match the "human" input.

**Comment by kd7lxl** [comment]
> Yeah that's exactly the Issue. The generated output often does not match the "human" input. We should just automate the whole process. Especially the releasing part of new versions

As a helm user, I often look first in values.yaml to see the available options rather than looking to the README.md. In this case, the values are not mentioned at all in the values.yaml. This breaks normal human usage as well as the helm-docs generator.

**Comment by ShuzZzle** [comment]
> > Yeah that's exactly the Issue. The generated output often does not match the "human" input. We should just automate the whole process. Especially the releasing part of new versions
> 
> As a helm user, I often look first in values.yaml to see the available options rather than looking to the README.md. In this case, the values are not mentioned at all in the values.yaml. This breaks normal human usage as well as the helm-docs generator.

Absolutely. Sorry I misread your comment, I thought you meant the README.md (which I was talking about). We will definitely try to keep the values.yml as the single source of truth.

**Review by cabrinha — APPROVED** [review]

**Pull request merged**
