### PR TITLE
Add monolithic mode options

### PR DESCRIPTION
**Pull request by TaylorMutch**
**What this PR does**:

Adds the ability to deploy the Cortex helm chart  in a "monolithic" mode

**Which issue(s) this PR fixes**:
Fixes https://github.com/cortexproject/cortex-helm-chart/issues/378

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by kd7lxl — COMMENTED** [review]
What you have prepared looks great and should work fine.

I am conflicted on whether this should just be its own chart. It disables almost the whole chart, so maybe it would be simpler to just have two variations of the chart, one for distributed and one for monolith.

**Review by kd7lxl — CHANGES_REQUESTED** [review]
I've thought about it a bit more and with the common configmap, I do see the value in including monolithic mode in the same chart. Some things I would like to see in this PR:
1. Consolidate the pod template to be common in the `Deployment` and `Statefulset` (or help me understand the value in maintaining them separately -- I'm trying to keep it DRY)
2. Add a section to the main part of the readme explaining monolithic mode and when you might use it, so it's more obvious to users that it's available.
3. Add test values for it in `ci/`

**Comment by TaylorMutch** [comment]
> 1. Consolidate the pod template to be common in the `Deployment` and `Statefulset` (or help me understand the value in maintaining them separately -- I'm trying to keep it DRY)

I think a pod template that is shared makes sense; I've seen that implemented elsewhere as well. I followed the pattern for the `ingester` templates which has them separated. I can implement a shared pod template for the monolith, and if we like that we could do that in the rest of the chart in a separate PR. What do you think?

**Comment by kd7lxl** [comment]
> if we like that we could do that in the rest of the chart in a separate PR. What do you think?

That would be nice, but it will depend on whether it can be done in a backwards compatible way. I haven't looked closely at the difference between the ingester deployment and statefulset to know yet if they could be updated to the same template without breaking anything. If something like the selector labels don't match it could present a problem.

**Pull request closed without merging**
