### PR TITLE
Update ingress.yaml 

### PR DESCRIPTION
**Pull request by dilipkk-foyernet**
Update apiVersion: networking.k8s.io/v1beta1 -> networking.k8s.io/v1 for Kubernetes versions 1.19+

### CODE REVIEW

**Comment by dilipkk-foyernet** [comment]
This fixes: https://github.com/cortexproject/cortex-helm-chart/issues/94

**Comment by khaines** [comment]
Update the changelog as well, please. Otherwise this LGTM! thank you for the PR.

**Comment by dilipkk-foyernet** [comment]
> Update the changelog as well, please. Otherwise this LGTM! thank you for the PR.

Done @khaines

**Comment by langecode** [comment]
Saw this was merged - nice - however, just a few comments.

For the `semverCompare` function to work the hyphen should be a dot line 4 and 6 in `ingess.yaml` (see also [Semantic Version Functions](https://helm.sh/docs/chart_template_guide/function_list/#semantic-version-functions)).

The structure of the ingress manifest has changed with Kubernetes 1.19 so it needs to rendered according to whether its 1.19 or previous ingress (see [ingress.yaml](https://github.com/langecode/cortex-helm-chart/blob/master/templates/ingress.yaml#L40))

**Comment by dilipkk-foyernet** [comment]
Thanks, @langecode, I just followed the pattern used previously and your point is valid. For now, we can keep it like this as it is working as expected with - also: https://semvercompare.azurewebsites.net/?version=1.14-0&version=1.14.1.

We need to refactor `.Capabilities.KubeVersion.GitVersion` to `.Capabilities.KubeVersion.Version` because of the following issue:
https://github.com/helm/charts/issues/20918, we can correct this error also at the same time

**Comment by dilipkk-foyernet** [comment]
I am not too sure about Go version, need to check that, yes in your fork it is showing as `>=1.19.0`.

**Comment by langecode** [comment]
Indeed, and I think I did that because we are running on a 1.19.x cluster and I got the deprecation warning mentioned in #94 testing out the deployment. Getting the deprecation warning Kubernetes is actually rewriting the resource `kind` which then causes Helm to loose the relation between what is deployed and what is actually there - and this can cause a pretty messy clean up.. been there, done that :-)

**Comment by dilipkk-foyernet** [comment]
https://play.golang.org/p/deMXSnOTHyZ
Tested with golang implementation also, it is working as expected.

**Pull request merged**
