### PR TITLE
Release v1.7.0

### PR DESCRIPTION
**Pull request by nschad**
**What this PR does**:
* [BUGFIX] Fix nginx extraContainers to indent correctly #373
* [DEPENDENCY] Update dependency nginx to v1.23 #375
* [DEPENDENCY] Update dependency kiwigrid/k8s-sidecar to v1.19.2 #370
* [DEPENDENCY] Update quay.io/cortexproject/cortex Docker tag to v1.13.0 #381
* [DEPENDENCY] Update kiwigrid/k8s-sidecar Docker tag to v1.19.4 #387
* [DEPENDENCY] Update kiwigrid/k8s-sidecar Docker tag to v1.19.5 #392

**Which issue(s) this PR fixes**:

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by gburton1** [comment]
HI @kd7lxl, can you +1 this new release cut? 🙏

**Review by kd7lxl — APPROVED** [review]
LGTM, thanks.

**Comment by gburton1** [comment]
Is there any extra step to actually cut the release? I still only see up to 1.6.0 available.

**Comment by nschad** [comment]
> Is there any extra step to actually cut the release? I still only see up to 1.6.0 available.

helm repo update? :D

image

**Pull request merged**
