### PR TITLE
[ENHANCEMENT] Add a nginx config to authenticate requests to query-frontend svc (multi-tenancy)

### PR DESCRIPTION
**Pull request by arjunbhandage**
**What this PR does**: Adds a nginx config to authenticate requests to query-frontend svc when multi-tenancy is enabled. see https://cortexmetrics.io/docs/api/#authentication and https://cortexmetrics.io/docs/api/#querier--query-frontend

**Which issue(s) this PR fixes**: None

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by arjunbhandage** [comment]
Need help here. The nginx config seems correct to me, but does not work when I deploy these changes. Followed the below blog for
https://www.nginx.com/blog/creating-nginx-rewrite-rules/
http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite

> Here’s a sample NGINX rewrite rule that uses the rewrite directive. It matches URLs that begin with the string /download and then include the /media/ or /audio/ directory somewhere later in the path. It replaces those elements with /mp3/ and adds the appropriate file extension, .mp3 or .ra. The $1 and $2 variables capture the path elements that aren't changing. As an example, /download/cdn-west/media/file1 becomes /download/cdn-west/mp3/file1.mp3. If there is an extension on the filename (such as .flv), the expression strips it off and replaces it with .mp3.

**Comment by ShuzZzle** [comment]
> Need help here. The nginx config seems correct to me, but does not work when I deploy these changes. Followed the below blog for
> https://www.nginx.com/blog/creating-nginx-rewrite-rules/
> http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
> 
> > Here’s a sample NGINX rewrite rule that uses the rewrite directive. It matches URLs that begin with the string /download and then include the /media/ or /audio/ directory somewhere later in the path. It replaces those elements with /mp3/ and adds the appropriate file extension, .mp3 or .ra. The $1 and $2 variables capture the path elements that aren't changing. As an example, /download/cdn-west/media/file1 becomes /download/cdn-west/mp3/file1.mp3. If there is an extension on the filename (such as .flv), the expression strips it off and replaces it with .mp3.

Any errors in the nginx pod?

**Comment by ShuzZzle** [comment]
> Need help here. The nginx config seems correct to me, but does not work when I deploy these changes. Followed the below blog for
> https://www.nginx.com/blog/creating-nginx-rewrite-rules/
> http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
> 
> > Here’s a sample NGINX rewrite rule that uses the rewrite directive. It matches URLs that begin with the string /download and then include the /media/ or /audio/ directory somewhere later in the path. It replaces those elements with /mp3/ and adds the appropriate file extension, .mp3 or .ra. The $1 and $2 variables capture the path elements that aren't changing. As an example, /download/cdn-west/media/file1 becomes /download/cdn-west/mp3/file1.mp3. If there is an extension on the filename (such as .flv), the expression strips it off and replaces it with .mp3.

Any error in the nginx pod?

**Comment by arjunbhandage** [comment]
> > Need help here. The nginx config seems correct to me, but does not work when I deploy these changes. Followed the below blog for
> > https://www.nginx.com/blog/creating-nginx-rewrite-rules/
> > http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
> > > Here’s a sample NGINX rewrite rule that uses the rewrite directive. It matches URLs that begin with the string /download and then include the /media/ or /audio/ directory somewhere later in the path. It replaces those elements with /mp3/ and adds the appropriate file extension, .mp3 or .ra. The $1 and $2 variables capture the path elements that aren't changing. As an example, /download/cdn-west/media/file1 becomes /download/cdn-west/mp3/file1.mp3. If there is an extension on the filename (such as .flv), the expression strips it off and replaces it with .mp3.
> 
> Any error in the nginx pod?

None. I find it really difficult to debug this. What tried is exec'd into the nginx pod. and ran the below command.

What I get:
```
# curl -i http://localhost:80/prometheus/api/v1/org/read
HTTP/1.1 404 Not Found
Server: nginx/1.21.1
Date: Thu, 05 Aug 2021 10:37:30 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19
Connection: keep-alive
X-Content-Type-Options: nosniff
```

What I expect from the command :
```
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.21.1
Date: Thu, 05 Aug 2021 10:38:28 GMT
Content-Length: 0
Connection: keep-alive
```

**Comment by arjunbhandage** [comment]
Not really required as we can configure the grafana data source with custom headers for authentication.
See https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
Custom HTTP headers for datasources

**Pull request closed without merging**
