### PR TITLE
max_look_back_period is removed from chunk.StoreConfig and compress_r…

### PR DESCRIPTION
**Pull request by Nitesh-vaidyanath**
…esponses is removed from  type frontend.CombinedFrontendConfig

### CODE REVIEW

**Comment by Nitesh-vaidyanath** [comment]
This is removed in cortex 1.9 version

**Comment by eMurgaNd** [comment]
I need these changes also.

**Comment by ShuzZzle** [comment]
Thank you for your contribution. #154 is a bit more complete in regards of upgrading the helm chart for cortex 1.9, so I would like to follow the topic there

**Comment by ShuzZzle** [comment]
Fixxed and merged in #154

**Pull request closed without merging**
